export const FORMULARIO_CLIMA = "FORMULARIO_CLIMA";
export const FORMULARIO_CLIMA_CERRAR = "FORMULARIO_CLIMA_CERRAR";
export const OBTENER_CLIMA = "OBTENER_CLIMA";

export const CALCULAR_TEMPERATURA_FAHRENHEIT =
	"CALCULAR_TEMPERATURA_FAHRENHEIT";
export const CALCULAR_TEMPERATURA_CELSIUS = "CALCULAR_TEMPERATURA_CELSIUS";
export const MODIFICAR_METRICA = "MODIFICAR_METRICA";

export const CARGAR_SPINNER = "CARGAR_SPINNER";
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";

export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
export const MENSAJE_ERROR = "MENSAJE_ERROR";
